enum CronAction {
    SEND_MEDIA = "SEND_MEDIA",
    SEND_STICKER = "SEND_STICKER",
    POST_WALKING_RESULTS = "POST_WALKING_RESULTS",
    DAILY_CAPYBARA = "DAILY_CAPYBARA"
}

export default CronAction;