import path from "node:path";

const ASSETS_PATH = path.join(__dirname, "assets");
const AUDIO_PATH = path.join(ASSETS_PATH, "audio");
const IMAGE_PATH = path.join(ASSETS_PATH, "image");
const VIDEO_PATH = path.join(ASSETS_PATH, "video");
const HTML_PATH = path.join(ASSETS_PATH, "html");

const DOOMPOD_HUG1_2023_FILE = "doompod-hug1-2023.gif"
const DOOMPOD_HUG2_2023_FILE = "doompod-hug2-2023.gif"
const DOOMPOD_KATIE_LETS_GO_2023_FILE = "doompod-katie-letsgo-2023.gif";
const DOOMPOD_TRISHAKE_2023_FILE = "doompod-trishake-2023.gif";
const LEGO_SCOOBE_FILE = "lego-scoob.png"
const RANDOM_ACTUALLY_REPLY_FILE = "random-actually-reply.gif";
const HALL_OFF_DOOT_REACTION_TEMPLATE = "reactionHallOfDootMessageTemplate.html";


const MONGO_GUILD_CHANNEL_MESSAGE_COLLECTION_NAME = "guild-channel-message"
const MONGO_GUILD_STICKER_COLLECTION_NAME = "guild-sticker"
const MONGO_BOT_ASSET_COLLECTION_NAME = "bot-asset"
const MONGO_CRON_SCHEDULE_COLLECTION_NAME = "cron-schedule"
const MONGO_CAPYBARA_COLLECTION_NAME = "capybara";
const MONGO_BOT_COMMAND_NAME = "bot-command"

const DAILY_CAPYBARA_URL = "https://capy.life/api/?days_ago=0";

const HTTP_RETRIES = 3;
const HTTP_WAIT_BETWEEN_RETRIES_MS = 10000;
const MY_CAPYBARA_NEXT_CAPY_BUTTON_ID = "MY_CAPYBARA_NEXT_CAPY_BUTTON_ID"
const MY_CAPYBARA_PREVIOUS_CAPY_BUTTON_ID = "MY_CAPYBARA_PREVIOUS_CAPY_BUTTON_ID"

export {
    ASSETS_PATH,
    AUDIO_PATH,
    IMAGE_PATH,
    VIDEO_PATH,
    HTML_PATH,
    DOOMPOD_HUG1_2023_FILE,
    DOOMPOD_HUG2_2023_FILE,
    DOOMPOD_KATIE_LETS_GO_2023_FILE,
    DOOMPOD_TRISHAKE_2023_FILE,
    RANDOM_ACTUALLY_REPLY_FILE,
    HALL_OFF_DOOT_REACTION_TEMPLATE,
    LEGO_SCOOBE_FILE,
    MONGO_GUILD_CHANNEL_MESSAGE_COLLECTION_NAME,
    MONGO_GUILD_STICKER_COLLECTION_NAME,
    MONGO_BOT_ASSET_COLLECTION_NAME,
    MONGO_CRON_SCHEDULE_COLLECTION_NAME,
    MONGO_CAPYBARA_COLLECTION_NAME,
    DAILY_CAPYBARA_URL,
    HTTP_RETRIES,
    HTTP_WAIT_BETWEEN_RETRIES_MS,
    MY_CAPYBARA_NEXT_CAPY_BUTTON_ID,
    MY_CAPYBARA_PREVIOUS_CAPY_BUTTON_ID,
    MONGO_BOT_COMMAND_NAME
}